# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 694c9c068173f5ce5b4ef012f5ac74b598beb1dbc743dd0dcc7f47f3c5f606403b26875c664947ff68257efe7a82ec03ebeff125819b64ea3d9d9eb8e5d8b638

test:
  secret_key_base: 708a095a025eaa1d2d6042fa8294a6b3c974885377b9e4971bd4c8bc82cfc42b644d203070040467d83221e2f95745a41c1e33bacf899767f652a2f1aed9f233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
